steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutrisnap-ai:v4', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nutrisnap-ai:v4']
images:
- 'gcr.io/$PROJECT_ID/nutrisnap-ai:v4'
options:
  logging: CLOUD_LOGGING_ONLY
